export const universities = [

    "Eötvös Loránd University",
    "Central European University",
    "University of Debrecen",
    "University of Pécs",
    "Budapest University of Technology and Economics",
    "Corvinus University of Budapest",
    "Semmelweis University",
    "University of Szeged",
    "Széchenyi István University",
    "University of Miskolc",
    "University of Physical Education",
    "Baptist Theological Seminary",
    "International Business School",
    "McDaniel College Budapest",
    "Moholy-Nagy University of Art and Design",
    "Óbuda University",
    "Premier Business School",
    "Reformed Theological University",
    "Tancsics Mihály Vocational College",
    "The Hungarian University of Fine Arts",
    "United Theological Seminary",
    "University of Physical Education",
    "Berzsenyi Dániel College",
    "Budapest Metropolitan University",
    "Budapest University of Jewish Studies",
    "College of Communication and Business",
    "European Business School Budapest",
    "Evangelical Lutheran Theological University",
    "Gothard Theological College",
    "Kodolányi János University of Applied Sciences",
    "Liszt Ferenc Academy of Music",
    "National Public Service University",
    "Perényi Péter Catholic University",
    "Saint Stephen University",
    "Sapientia Hungarian University of Transylvania",
    "Szent Ignác Catholic Student Hall",
    "Szent István University",
    "Szent Kereszt Catholic University",
    "Szentpéteri Martin Lutheran Evangelical Theological College",
    "Tomori Pál College",
    "University of Dunaújváros",
    "University of Kaposvár",
    "University of Pécs",
    "University of Public Service",
    "University of Sopron",
    "University of West Hungary",
    "University of Zena",
    "West Hungarian University",
    "David Sinyard Student Apartment College",
    "Hungarian University of Fine Arts",
    "Janus Pannonius University",
    "Károly Róbert College",
    "Kodolányi János College",
    "Kossuth Lajos Student Dormitory",
    "Mosonmagyaróvár Vásári Pályaműhely Secondary School",
    "National University of Public Service",
    "Pázmány Péter Catholic University",
    "SárgaFüzet Theatre School",
    "Szolnok University College",
    "The Szent István Institute",
];
export const cities = [

    "Budapest",
    "Debrecen",
    "Pécs",
    "Miskolc",
    "Szeged",
    "Győr",
    "Veszprém",
    "Szombathely",
    "Dunaújváros",
    "Kaposvár",
    "Sopron",
    "Szentendre",
    "Zalaegerszeg",
    "Eger",
    "Kecskemét",
    "Tatabánya",
    "Salgótarján",
    "Hódmezővásárhely",
    "Nagykanizsa",
    "Szolnok",
    "Székesfehérvár",
    "Szekszárd",
    "Pécel",
    "Sárvár",
    "Ajka",
    "Ózd",
    "Várpalota",
    "Dabas",
    "Orosháza",
    "Kiskunhalas",
    "Hajdúböszörmény",
    "Keszthely",
    "Hatvan",
    "Kalocsa",
    "Cegléd",
    "Szarvas",
    "Baja",
    "Gödöllő",
    "Gyöngyös",
    "Monor",
    "Nagyatád",
    "Mezőkövesd",
    "Vác",
    "Pilisvörösvár",
    "Esztergom",
    "Sárbogárd",
    "Veszprémvarsány",
    "Zamárdi",
    "Gyömrő",
    "Hatvanbánhida",
    "Tapolca",
    "Ceglédbercel",
    "Szabadszállás",
    "Nagytarcsa",
    "Vácduka",
];
export const educationLevels = ["Bachelor's Degree", "Master's Degree", "PhD"];
